#!/usr/bin/env python3
"""Génère devis-en.html (£, mêmes chiffres) depuis le template simulateur FR.
Usage: make_devis_en.py <out_dir>"""
import base64, sys
OUT = sys.argv[1] if len(sys.argv) > 1 else "/root/catalogue-models"
SKILL = "/root/.claude/skills/pdf-lou"
h = open(f"{SKILL}/templates/simulateur-devis.html").read()

REP = [
 ('<html lang="fr">','<html lang="en">'),
 ('<title>Lou Denim — Simulateur de devis</title>','<title>Lou Denim — Quote simulator</title>'),
 ('Directeur artistique IA','AI Creative Director'),
 ('<h1>Simulateur de devis</h1>','<h1>Quote simulator</h1>'),
 ('<p>Services créatifs IA</p>','<p>AI creative services</p>'),
 ("Composez votre projet ci-dessous : le montant se met à jour en direct. C'est une <b>estimation</b>, votre devis final est établi par Lou Denim. Une fois validé, envoyez le récapitulatif.",
  "Build your project below: the amount updates live. This is an <b>estimate</b>, your final quote is set by Lou Denim. Once you're happy, send the summary."),
 ('>Vos coordonnées<','>Your details<'),
 ('placeholder="Nom / société"','placeholder="Name / company"'),
 ('>Vidéo par IA<','>AI video<'),
 ('>Type de scène<','>Scene type<'),
 ("Studio = fond neutre · Environnement = lieu réel · Un service ? son lieu / sa façade fait office de produit.<br>\n        Personnage : casting, habillement, accessoires et mise en scène <b>inclus</b>. Choisissez vos visages dans le <a href=\"__LINK_CATALOGUE__\" target=\"_blank\" rel=\"noopener\">catalogue de modèles</a>.",
  "Studio = plain background · Environment = real location · A service? its place / facade acts as the product.<br>\n        Characters: casting, wardrobe, props and staging <b>included</b>. Pick your faces in the <a href=\"__LINK_CATALOGUE__\" target=\"_blank\" rel=\"noopener\">model catalogue</a>."),
 ('>Durée<','>Duration<'),
 ('>Résolution<','>Resolution<'),
 ('Style visuel <span class="pr" style="font-weight:400">— même tarif</span>','Visual style <span class="pr" style="font-weight:400">— same rate</span>'),
 ('>Effets &amp; transformations<','>Effects &amp; transformations<'),
 ('>Son &amp; finitions<','>Sound &amp; finishing<'),
 ('>Personnages<','>Characters<'),
 ('>Autres options<','>Other options<'),
 ('Immobilier &amp; lieux <span style="font-weight:400;letter-spacing:.04em;font-size:10px;opacity:.7">— à partir de vos photos</span>',
  'Real estate &amp; places <span style="font-weight:400;letter-spacing:.04em;font-size:10px;opacity:.7">— from your photos</span>'),
 ('>Visite animée du bien<','>Animated property tour<'),
 ('Chaque pièce prend vie : mouvements de caméra, transitions, montage sur musique.','Every room comes alive: camera moves, transitions, edited to music.'),
 ('Photos du bien à réaliser ? Prise de vue sur place possible.','Need photos of the property? On-location shoot available.'),
 ('Images par IA <span style="font-weight:400;letter-spacing:.04em;font-size:10px;opacity:.7">— lots de 5 minimum</span>',
  'AI images <span style="font-weight:400;letter-spacing:.04em;font-size:10px;opacity:.7">— sets of 5 minimum</span>'),
 ("Chaque vidéo est livrée finie&nbsp;: <b>étalonnée, montée, sonorisée</b> (musique d'illustration et effets sonores inclus) et exportée au format final de votre plateforme.",
  "Every video is delivered finished: <b>colour-graded, edited, sound-designed</b> (library music and sound effects included) and exported in your platform's final format."),
 ('>Votre estimation<','>Your estimate<'),
 ('<b>Total estimé</b>','<b>Estimated total</b>'),
 ('Estimation indicative HT. Le devis final est établi par Lou Denim selon la complexité du brief. Acompte 50 % avant démarrage.',
  'Indicative estimate, excl. VAT. The final quote is set by Lou Denim based on brief complexity. 50% deposit before we start.'),
 # ---- Packs dégressifs (upsell sous l'estimation) ----
 ('Configurez une vidéo pour voir les tarifs de pack (3 ou 5 vidéos).',
  'Configure a video to see pack rates (3 or 5 videos).'),
 ('<div class="packlab">Vous en voulez plusieurs&nbsp;?</div>',
  '<div class="packlab">Ordering several&nbsp;?</div>'),
 ('<div class="t">Pack de 3 vidéos</div>','<div class="t">Pack of 3 videos</div>'),
 ('<div class="t">Pack de 5 vidéos</div>','<div class="t">Pack of 5 videos</div>'),
 ('<small> / vidéo</small>','<small> / video</small>'),
 ('<div class="tt">3 vidéos&nbsp;: ','<div class="tt">3 videos: '),
 ('<div class="tt">5 vidéos&nbsp;: ','<div class="tt">5 videos: '),
 ('<div class="s">−15 %</div>','<div class="s">−15%</div>'),
 ('<div class="s">−25 %</div>','<div class="s">−25%</div>'),
 ('Tarifs indicatifs pour des vidéos similaires, ajustés selon vos besoins.',
  'Indicative rates for similar videos, adjusted to your needs.'),
 ('>Envoyer à Lou Denim</button>','>Send to Lou Denim</button>'),
 ('>Copier le récapitulatif</button>','>Copy the summary</button>'),
 ('>Catalogue de modèles IA</a>','>AI model catalogue</a>'),
 ('__LINK_GRILLE__" target="_blank" rel="noopener">Grille tarifaire</a>','__LINK_GRILLE__" target="_blank" rel="noopener">Rate card (PDF)</a>'),
 ("Urgence : livraison sous 48 h, +40 % sur la vidéo (estimation).","Rush: 48-hour delivery, +40% on the video (estimate)."),
 # ---- JS : libellés & devise ----
 ("studio:{label:'Produit seul — studio'","studio:{label:'Product only — studio'"),
 ("environnement:{label:'Produit en environnement'","environnement:{label:'Product in an environment'"),
 ("perso1:{label:'Produit + 1 personnage'","perso1:{label:'Product + 1 character'"),
 ("perso2:{label:'Produit + 2 personnages'","perso2:{label:'Product + 2 characters'"),
 ("const RES={ '720':{label:'HD 720p — inclus',mult:1.0}, '1080':{label:'Full HD 1080p — +20 %',mult:1.2}, '4k':{label:'4K Upscale — +50 %',mult:1.5} };",
  "const RES={ '720':{label:'HD 720p — included',mult:1.0}, '1080':{label:'Full HD 1080p — +20%',mult:1.2}, '4k':{label:'4K Upscale — +50%',mult:1.5} };"),
 ("const STYLES=['Photoréaliste','Animation 3D','Dessin animé 2D'];","const STYLES=['Photorealistic','3D animation','2D cartoon'];"),
 ("morphing:{label:'Morphing / transformation',price:150},","morphing:{label:'Morphing / transformation',price:150},"),
 ("decor:{label:'Changement de décor / saison',price:150},","decor:{label:'Set / season change',price:150},"),
 ("lumiere:{label:'Changement de lumière (jour↔nuit, néon…)',price:150},","lumiere:{label:'Relighting (day↔night, neon…)',price:150},"),
 ("swap:{label:'Remplacement d’objet / couleur produit',price:150},","swap:{label:'Object / product-colour swap',price:150},"),
 ("motion:{label:'Motion design — titres animés, habillage',price:150},","motion:{label:'Motion design — animated titles, graphics',price:150},"),
 ("voix:{label:'Voix off IA (FR/EN/ES)',price:100,des:true},","voix:{label:'AI voice-over (FR/EN/ES)',price:100,des:true},"),
 ("musique:{label:'Musique originale & sound design sur mesure',price:100,des:true},","musique:{label:'Custom music & sound design',price:100,des:true},"),
 ("endcard:{label:'Carte de fin — logo animé + signature sonore',price:150},","endcard:{label:'End card — animated logo + audio signature',price:150},"),
 ("soustitres:{label:'Sous-titres',price:75},","soustitres:{label:'Captions / subtitles',price:75},"),
 ("parlant:{label:'Personnage qui parle face caméra — voix + synchro labiale',price:100,des:true},","parlant:{label:'Character speaking to camera — voice + lip-sync',price:100,des:true},"),
 ("dialog2:{label:'Dialogue entre 2 personnages',price:200,des:true},","dialog2:{label:'2-character dialogue',price:200,des:true},"),
 ("exclu:{label:'Exclusivité personnage sur mesure — réservé à votre marque',price:300},","exclu:{label:'Custom-character exclusivity — reserved to your brand',price:300},"),
 ("storyboard:{label:'Storyboard — validation avant production',price:150,des:true},","storyboard:{label:'Storyboard — sign-off before production',price:150,des:true},"),
 ("script:{label:'Script / concept',price:200,des:true},","script:{label:'Script / concept',price:200,des:true},"),
 ("prod:{label:'Produit seul (lot de 5)',price:250},","prod:{label:'Product only (set of 5)',price:250},"),
 ("perso:{label:'1 personnage + produit (lot de 5)',price:380},","perso:{label:'1 character + product (set of 5)',price:380},"),
 ("multi:{label:'2–3 personnages + produit (lot de 5)',price:600},","multi:{label:'2–3 characters + product (set of 5)',price:600},"),
 ("lot10:{label:'Lot de 10 — campagne complexe',price:900},","lot10:{label:'Set of 10 — complex campaign',price:900},"),
 ("function eur(n){return n.toLocaleString('fr-FR')+' €';}","function eur(n){return '£'+n.toLocaleString('en-GB');}"),
 ("`<div class=\"qtyrow\"><span>Tours de révision supplémentaires <span class=\"pr\">150 € / tour (2 inclus)</span></span>","`<div class=\"qtyrow\"><span>Extra revision rounds <span class=\"pr\">£150 / round (2 included)</span></span>"),
 ("Urgence — livraison 48 h <span class=\"pr\">+40 %</span>","Rush — 48 h delivery <span class=\"pr\">+40%</span>"),
 ("Personnage ajouté — mise en vie du lieu <span class=\"pr\">+${IMMO.perso} €</span>","Character added — bringing the place to life <span class=\"pr\">+£${IMMO.perso}</span>"),
 ("`<div class=\"qtyrow\"><span>Embellissement photo <span class=\"pr\">dès ${IMMO.embellissement} € / photo</span></span>","`<div class=\"qtyrow\"><span>Photo enhancement <span class=\"pr\">from £${IMMO.embellissement} / photo</span></span>"),
 ("`<div class=\"qtyrow\"><span>Home staging virtuel <span class=\"pr\">dès ${IMMO.staging} € / photo</span></span>","`<div class=\"qtyrow\"><span>Virtual home staging <span class=\"pr\">from £${IMMO.staging} / photo</span></span>"),
 ("${d} <span class=\"pr\">${IMMO.p[i]} €</span>","${d} <span class=\"pr\">£${IMMO.p[i]}</span>"),
 ("${v.des?'dès ':''}+${v.price} €","${v.des?'from ':''}+£${v.price}"),
 ("${v.price} € / lot","£${v.price} / set"),
 ("lines.push(['Vidéo — choisissez scène + durée',null]);","lines.push(['Video — pick scene + duration',null]);"),
 ("lines.push([`Style : ${STYLES[state.style]}`,0]);","lines.push([`Style: ${STYLES[state.style]}`,0]);"),
 ("lines.push(['Urgence +40 %',u]);","lines.push(['Rush +40%',u]);"),
 ("lines.push([`Révisions supplémentaires × ${state.revision}`,r]);","lines.push([`Extra revisions × ${state.revision}`,r]);"),
 ("lines.push([`Visite animée du bien · ${DURS[state.immoDur]}`,p]);","lines.push([`Animated property tour · ${DURS[state.immoDur]}`,p]);"),
 ("lines.push(['Immobilier : personnage ajouté',IMMO.perso]);","lines.push(['Real estate: character added',IMMO.perso]);"),
 ("lines.push([`Embellissement photo × ${state.immoEmb}`,s]);","lines.push([`Photo enhancement × ${state.immoEmb}`,s]);"),
 ("lines.push([`Home staging virtuel × ${state.immoStag}`,s]);","lines.push([`Virtual home staging × ${state.immoStag}`,s]);"),
 ("`Résolution ${RES[state.res].label.split('—')[0].trim()}`","`Resolution ${RES[state.res].label.split('—')[0].trim()}`"),
 ("'<div class=\"li muted\"><span>Aucune sélection pour l’instant</span></div>'","'<div class=\"li muted\"><span>Nothing selected yet</span></div>'"),
 ("const lines=['DEMANDE DE DEVIS — LOU DENIM','','Client : '+name,'Email : '+mail,''];","const lines=['QUOTE REQUEST — LOU DENIM','','Client: '+name,'Email: '+mail,''];"),
 ("lines.push('• '+l+' : '+(v===null?'à préciser':(v===0?'inclus':eur(v))));","lines.push('• '+l+': '+(v===null?'TBD':(v===0?'included':eur(v))));"),
 ("lines.push('TOTAL ESTIMÉ : '+eur(window._total||0)+' (HT, estimation)');","lines.push('ESTIMATED TOTAL: '+eur(window._total||0)+' (excl. VAT, estimate)');"),
 ("alert('Récapitulatif copié — collez-le dans un email à lou@loudenim.com')","alert('Summary copied — paste it into an email to lou@loudenim.com')"),
 ("subject:'Demande de devis — '+name,","subject:'Quote request (EN) — '+name,"),
 ("from_name:'Simulateur Lou Denim',","from_name:'Lou Denim quote simulator',"),
 ("alert('Merci d’indiquer votre nom et votre email avant d’envoyer votre demande.')","alert('Please enter your name and email before sending.')"),
 ("btn.textContent='Envoi…'","btn.textContent='Sending…'"),
 ("'<h3>Merci&nbsp;!</h3><p style=\"font-size:13px;line-height:1.6\">Votre demande a bien été envoyée à Lou Denim. Vous recevrez un devis rapidement.</p>'",
  "'<h3>Thank you!</h3><p style=\"font-size:13px;line-height:1.6\">Your request has been sent to Lou Denim. You will receive a quote shortly.</p>'"),
 ("alert('Envoi impossible : '+(d.message||'réessayez.'))","alert('Could not send: '+(d.message||'please retry.'))"),
 ("alert('Problème réseau — réessayez, ou utilisez « Copier le récapitulatif » et envoyez-le à lou@loudenim.com.')","alert('Network problem — retry, or use Copy the summary and email it to lou@loudenim.com.')"),
 ("(v===0?'inclus':eur(v))","(v===0?'included':eur(v))"),
 ("footer>Lou Denim — loudenim.com","footer>Lou Denim — loudenim.com"),
 ('Envie de voir&nbsp;? <a href="portfolio.html">Le travail en images</a>','Want to see? <a href="portfolio-en.html">The work</a>'),
]

# --- pairs for the 2026 redesign (3 formats + slider + reset + mobile bar + topnav in template) ---
REP += [
 ('href="home.html">Accueil</a>','href="home-en.html">Home</a>'),
 ('href="portfolio.html">Portfolio</a>','href="portfolio-en.html">Portfolio</a>'),
 ('href="modeles.html">Modèles</a>','href="models-en.html">Models</a>'),
 ('href="rate.html">Grille tarifaire</a>','href="rate-en.html">Rate card</a>'),
 ('class="on" href="simulator.html">Simulateur</a>','class="on" href="simulator-en.html">Simulator</a>'),
 ('href="brief.html">Brief vidéo</a>','href="brief-en.html">Video brief</a>'),
 ('<div class="langs"><a class="" href="simulator-en.html">EN</a><a class="on" href="simulator.html">FR</a></div>',
  '<div class="langs"><a class="on" href="simulator-en.html">EN</a><a class="" href="simulator.html">FR</a></div>'),
 ('1 · Durée de la vidéo','1 · Video length'),
 ('2 · Que montre votre vidéo ?','2 · What does your video show?'),
 ("""Produit = aussi un service (son lieu, son enseigne, sa fa&ccedil;ade). Les deux premiers formats sont sur fond neutre
        &mdash; le lieu r&eacute;el s&rsquo;ajoute &agrave; l&rsquo;&eacute;tape 3. <b>UGC</b> : 1 personnage qui parle face cam&eacute;ra
        (voix + synchro labiale) et 1 lieu r&eacute;el <b>inclus</b>.""",
  """Product = also a service (its place, its sign, its facade). The first two formats are on a plain background
        &mdash; the real location is added at step 3. <b>UGC</b>: 1 character talking to camera (voice + lip-sync) and 1 real location <b>included</b>."""),
 ('3 · Ajoutez à votre scène','3 · Add to your scene'),
 ('Personnage : casting, tenue &amp; mise en scène <b>inclus</b>. Choisissez un visage dans le <a href="modeles.html" target="_blank" rel="noopener">catalogue de modèles</a>, ou je le crée pour vous — même tarif. Pour le réserver à votre marque, voir <b>Exclusivité</b> dans la section Personnages.',
  'Character: casting, wardrobe &amp; staging <b>included</b>. Pick a face in the <a href="models-en.html" target="_blank" rel="noopener">model catalogue</a>, or I create one for you — same rate. To reserve it for your brand, see <b>Exclusivity</b> in the Characters section.'),
 ('>Le produit seul</label>','>The product on its own</label>'),
 ('>Le produit + 1 personnage</label>','>The product + 1 character</label>'),
 ('>UGC — face cam&eacute;ra</label>','>UGC — talking to camera</label>'),
 ('Environnements <span class="pr">+${ENV_PRICE} € / environnement</span>','Environments <span class="pr">+£${ENV_PRICE} / environment</span>'),
 ('Personnages suppl&eacute;mentaires <span class="pr">+${CHAR_PRICE} € / personnage</span>','Extra characters <span class="pr">+£${CHAR_PRICE} / character</span>'),
 ('Produits / services en plus <span class="pr">+${PROD_PRICE} € / unité</span>','Extra products / services <span class="pr">+£${PROD_PRICE} / unit</span>'),
 ('// produit/service — studio','// product/service — plain background'),
 ('// produit/service + 1 personnage','// product/service + 1 character'),
 ('// UGC — personnage qui parle + lieu réel inclus','// UGC — talking character + real location included'),
 ('`UGC — face caméra (parole + lieu inclus) · ${VDURS[state.dur]}`','`UGC — talking to camera (speech + location included) · ${VDURS[state.dur]}`'),
 ('`Le produit + 1 personnage · ${VDURS[state.dur]}`','`The product + 1 character · ${VDURS[state.dur]}`'),
 ('`Le produit seul · ${VDURS[state.dur]}`','`The product on its own · ${VDURS[state.dur]}`'),
 ('`Environnements × ${state.envs}`','`Environments × ${state.envs}`'),
 ('`Produits / services en plus × ${state.prodsExtra}`','`Extra products / services × ${state.prodsExtra}`'),
 ('<h3 style="margin:0">Votre estimation</h3>','<h3 style="margin:0">Your estimate</h3>'),
 ('&#8634; Réinitialiser','&#8634; Reset'),
 ('<span class="mtot">Total estimé<b id="amt2">0 €</b></span>','<span class="mtot">Estimated total<b id="amt2">0 £</b></span>'),
]
REP += [
 ('<a href="home.html"><img src="__LOGO_SRC__" alt="Lou Denim"></a>','<a href="home-en.html"><img src="__LOGO_SRC__" alt="Lou Denim"></a>'),
 ('<h2 class="band">Immobilier &amp; lieux <span style="font-weight:400;letter-spacing:.04em;font-size:11px;opacity:.7">— à partir de vos photos</span></h2>',
  '<h2 class="band">Real estate &amp; places <span style="font-weight:400;letter-spacing:.04em;font-size:11px;opacity:.7">— from your photos</span></h2>'),
 ('<h2 class="band">Images par IA <span style="font-weight:400;letter-spacing:.04em;font-size:11px;opacity:.7">— lots de 5 minimum</span></h2>',
  '<h2 class="band">AI images <span style="font-weight:400;letter-spacing:.04em;font-size:11px;opacity:.7">— sets of 5 minimum</span></h2>'),
 ('<a href="modeles.html" target="_blank" rel="noopener">AI model catalogue</a>','<a href="models-en.html" target="_blank" rel="noopener">AI model catalogue</a>'),
 ('<a href="rate.html" target="_blank" rel="noopener">Grille tarifaire</a>','<a href="Rate_Card_LouDenim.pdf" target="_blank" rel="noopener">Rate card (PDF)</a>'),
 ("'<h3>Merci&nbsp;!</h3><p style=\"font-size:14.5px;line-height:1.6\">Votre demande a bien été envoyée à Lou Denim. Vous recevrez un devis rapidement.</p>'",
  "'<h3>Thank you!</h3><p style=\"font-size:14.5px;line-height:1.6\">Your request has been sent to Lou Denim. You will receive a quote shortly.</p>'"),
]
# the extra-characters receipt line carries a literal \u00e9 escape inside the JS template string
REP += [('`Personnages suppl\\u00e9mentaires × ${state.chars}`','`Extra characters × ${state.chars}`')]

missed = 0
for a,b in REP:
    if a in h: h = h.replace(a,b)
    elif a != b: missed += 1; print('  (absent):', a[:70])
b64 = "data:image/svg+xml;base64," + base64.b64encode(open(f"{SKILL}/assets/lou-denim-logo.svg","rb").read()).decode()
h = h.replace('__LOGO_SRC__', b64).replace('__LINK_CATALOGUE__','models-en.html').replace('__LINK_GRILLE__','Rate_Card_LouDenim.pdf')
open(f"{OUT}/simulator-en.html",'w').write(h)
print('simulator-en.html ok — non trouvés:', missed)
